package PisP.inout.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;

public class Inout_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("PisP.inout");

  public Inout_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new Import_Legacy_Action());
    // groups
  }
}
