package PisP.inout.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class Shortcuts_KeymapChanges extends BaseKeymapChanges {
  public Shortcuts_KeymapChanges() {
    add("PisP.inout.plugin.Import_Legacy_Action", "ctrl shift I");
  }
  @Override
  public String getScheme() {
    return "$default";
  }

}
