package PisP.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_LatticeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LatticeEnum() {
    super(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37af372fL, "LatticeEnum", "r:c0c44ecb-4459-46b9-b227-3b76e96cebff(PisP.structure)/12618812418373423");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CubicLattice2D_0 = new EnumerationDescriptor.MemberDescriptor("CubicLattice2D", "2D cubic lattice", 0x2cd4be37af3730L, "r:c0c44ecb-4459-46b9-b227-3b76e96cebff(PisP.structure)/12618812418373424");
  private final EnumerationDescriptor.MemberDescriptor myMember_CubicLattoce3D_0 = new EnumerationDescriptor.MemberDescriptor("CubicLattoce3D", "3D cubic lattice", 0x2e8846265a55f50eL, "r:c0c44ecb-4459-46b9-b227-3b76e96cebff(PisP.structure)/3353007053115618574");
  private final EnumerationDescriptor.MemberDescriptor myMember_FCCLattice_0 = new EnumerationDescriptor.MemberDescriptor("FCCLattice", "FCC lattice", 0x2cd4be37af5e88L, "r:c0c44ecb-4459-46b9-b227-3b76e96cebff(PisP.structure)/12618812418383496");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37af372fL, 0x2cd4be37af3730L, 0x2e8846265a55f50eL, 0x2cd4be37af5e88L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CubicLattice2D_0, myMember_CubicLattoce3D_0, myMember_FCCLattice_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CubicLattice2D":
        return myMember_CubicLattice2D_0;
      case "CubicLattoce3D":
        return myMember_CubicLattoce3D_0;
      case "FCCLattice":
        return myMember_FCCLattice_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
