package PisP.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BagOfPieces = 0;
  public static final int Coordinate = 1;
  public static final int DescriptionComment = 2;
  public static final int IDescriptionComment = 3;
  public static final int Location = 4;
  public static final int Piece = 5;
  public static final int PieceReference = 6;
  public static final int Puzzle = 7;
  public static final int Shape = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L);
    builder.put(0x2cd4be37ada031L, BagOfPieces);
    builder.put(0x2cd4be37adda67L, Coordinate);
    builder.put(0x1b3c19e094c6322eL, DescriptionComment);
    builder.put(0x1b3c19e094c62282L, IDescriptionComment);
    builder.put(0x2cd4be37adb89fL, Location);
    builder.put(0x2cd4be37ae0ae9L, Piece);
    builder.put(0x2cd4be37ae02bdL, PieceReference);
    builder.put(0x2cd4be37abf69bL, Puzzle);
    builder.put(0x2cd4be37ada4e2L, Shape);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
