// Auto-generated by PisP.gen.code2solver.Cpp
#include <bitset>
#include <iostream>
#include <chrono>
using namespace std;
using namespace std::chrono;

bitset<6> q;
int i = 0;

void Sinfty() {
  i++;
}
void S3() {
  if (!q[3]) {
    Sinfty();
  }
  if (q[3]) {
    q.reset(3);
    if (q[5]) {
      q.reset(5);
      Sinfty();
      q.set(5);
    }
    q.set(3);
  }
}
void S2() {
  if (!q[2]) {
    S3();
  }
  if (q[2]) {
    q.reset(2);
    if (q[5]) {
      q.reset(5);
      S3();
      q.set(5);
    }
    q.set(2);
  }
}
void S1() {
  if (!q[1]) {
    S2();
  }
  if (q[1]) {
    q.reset(1);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[4]) {
          q.reset(4);
          S2();
          q.set(4);
        }
        q.set(3);
      }
      q.set(2);
    }
    if (q[5]) {
      q.reset(5);
      S2();
      q.set(5);
    }
    q.set(1);
  }
}
void S0() {
  if (!q[0]) {
    S1();
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[4]) {
          q.reset(4);
          S1();
          q.set(4);
        }
        q.set(2);
      }
      if (q[3]) {
        q.reset(3);
        if (q[4]) {
          q.reset(4);
          S1();
          q.set(4);
        }
        q.set(3);
      }
      q.set(1);
    }
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[4]) {
          q.reset(4);
          S1();
          q.set(4);
        }
        q.set(3);
      }
      q.set(2);
    }
    if (q[5]) {
      q.reset(5);
      S1();
      q.set(5);
    }
    q.set(0);
  }
}

int main() {
  cout << "Solving 3-1 pyramid..." << endl;
  q.set(); /* q = A */
  auto start = high_resolution_clock::now();
  S0(); /* start solver */
  auto stop = high_resolution_clock::now();
  auto duration = duration_cast<microseconds>(stop - start);
  cout << "Found " << i << " solutions in " << duration.count() << " microseconds.";
  return 0;
}
