// Auto-generated by PisP.gen.code2solver.Cpp
#include <bitset>
#include <iostream>
#include <chrono>
using namespace std;
using namespace std::chrono;

bitset<10> q;
int i = 0;

void Sinfty() {
  i++;
  //cout << "\r" << i;
}
void S9() {
  if (!q[9]) {
    Sinfty();
  }
}
void S8() {
  if (!q[8]) {
    S9();
  }
}
void S7() {
  if (!q[7]) {
    S8();
  }
}
void S6() {
  if (!q[6]) {
    S7();
  }
}
void S5() {
  if (!q[5]) {
    S6();
  }
  if (q[5]) {
    q.reset(5);
    if (q[6]) {
      q.reset(6);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S6();
          q.set(9);
        }
        q.set(7);
      }
      q.set(6);
    }
    q.set(5);
  }
}
void S4() {
  if (!q[4]) {
    S5();
  }
  if (q[4]) {
    q.reset(4);
    if (q[5]) {
      q.reset(5);
      if (q[6]) {
        q.reset(6);
        if (q[9]) {
          q.reset(9);
          S5();
          q.set(9);
        }
        q.set(6);
      }
      q.set(5);
    }
    q.set(4);
  }
  if (q[4]) {
    q.reset(4);
    if (q[5]) {
      q.reset(5);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S5();
          q.set(9);
        }
        q.set(7);
      }
      q.set(5);
    }
    q.set(4);
  }
  if (q[4]) {
    q.reset(4);
    if (q[6]) {
      q.reset(6);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S5();
          q.set(9);
        }
        q.set(7);
      }
      q.set(6);
    }
    q.set(4);
  }
}
void S3() {
  if (!q[3]) {
    S4();
  }
  if (q[3]) {
    q.reset(3);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S4();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(3);
  }
  if (q[3]) {
    q.reset(3);
    if (q[5]) {
      q.reset(5);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S4();
          q.set(9);
        }
        q.set(7);
      }
      q.set(5);
    }
    q.set(3);
  }
  if (q[3]) {
    q.reset(3);
    if (q[6]) {
      q.reset(6);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S4();
          q.set(9);
        }
        q.set(7);
      }
      q.set(6);
    }
    q.set(3);
  }
}
void S2() {
  if (!q[2]) {
    S3();
  }
  if (q[2]) {
    q.reset(2);
    if (q[3]) {
      q.reset(3);
      if (q[4]) {
        q.reset(4);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S3();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(4);
      }
      q.set(3);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[3]) {
      q.reset(3);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S3();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(3);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[3]) {
      q.reset(3);
      if (q[6]) {
        q.reset(6);
        if (q[9]) {
          q.reset(9);
          S3();
          q.set(9);
        }
        q.set(6);
      }
      q.set(3);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[3]) {
      q.reset(3);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S3();
          q.set(9);
        }
        q.set(7);
      }
      q.set(3);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S3();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[4]) {
      q.reset(4);
      if (q[6]) {
        q.reset(6);
        if (q[9]) {
          q.reset(9);
          S3();
          q.set(9);
        }
        q.set(6);
      }
      q.set(4);
    }
    q.set(2);
  }
  if (q[2]) {
    q.reset(2);
    if (q[6]) {
      q.reset(6);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S3();
          q.set(9);
        }
        q.set(7);
      }
      q.set(6);
    }
    q.set(2);
  }
}
void S1() {
  if (!q[1]) {
    S2();
  }
  if (q[1]) {
    q.reset(1);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[5]) {
          q.reset(5);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S2();
              q.set(8);
            }
            q.set(7);
          }
          q.set(5);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S2();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[9]) {
          q.reset(9);
          S2();
          q.set(9);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[3]) {
      q.reset(3);
      if (q[4]) {
        q.reset(4);
        if (q[5]) {
          q.reset(5);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S2();
              q.set(8);
            }
            q.set(7);
          }
          q.set(5);
        }
        q.set(4);
      }
      q.set(3);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[3]) {
      q.reset(3);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S2();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(3);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[3]) {
      q.reset(3);
      if (q[5]) {
        q.reset(5);
        if (q[9]) {
          q.reset(9);
          S2();
          q.set(9);
        }
        q.set(5);
      }
      q.set(3);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[3]) {
      q.reset(3);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S2();
          q.set(9);
        }
        q.set(7);
      }
      q.set(3);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S2();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[9]) {
          q.reset(9);
          S2();
          q.set(9);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(1);
  }
  if (q[1]) {
    q.reset(1);
    if (q[5]) {
      q.reset(5);
      if (q[7]) {
        q.reset(7);
        if (q[9]) {
          q.reset(9);
          S2();
          q.set(9);
        }
        q.set(7);
      }
      q.set(5);
    }
    q.set(1);
  }
}
void S0() {
  if (!q[0]) {
    S1();
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[3]) {
          q.reset(3);
          if (q[4]) {
            q.reset(4);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(4);
          }
          q.set(3);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[3]) {
          q.reset(3);
          if (q[5]) {
            q.reset(5);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(5);
          }
          q.set(3);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[3]) {
          q.reset(3);
          if (q[6]) {
            q.reset(6);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(6);
          }
          q.set(3);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[3]) {
          q.reset(3);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(3);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[4]) {
          q.reset(4);
          if (q[5]) {
            q.reset(5);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(5);
          }
          q.set(4);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[4]) {
          q.reset(4);
          if (q[6]) {
            q.reset(6);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(6);
          }
          q.set(4);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[2]) {
        q.reset(2);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(2);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[3]) {
        q.reset(3);
        if (q[4]) {
          q.reset(4);
          if (q[5]) {
            q.reset(5);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(5);
          }
          q.set(4);
        }
        q.set(3);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[3]) {
        q.reset(3);
        if (q[5]) {
          q.reset(5);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(5);
        }
        q.set(3);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[3]) {
        q.reset(3);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(3);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[4]) {
        q.reset(4);
        if (q[5]) {
          q.reset(5);
          if (q[6]) {
            q.reset(6);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(6);
          }
          q.set(5);
        }
        q.set(4);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[4]) {
        q.reset(4);
        if (q[5]) {
          q.reset(5);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(5);
        }
        q.set(4);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[4]) {
        q.reset(4);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(4);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[1]) {
      q.reset(1);
      if (q[5]) {
        q.reset(5);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(5);
      }
      q.set(1);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[4]) {
          q.reset(4);
          if (q[6]) {
            q.reset(6);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(6);
          }
          q.set(4);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[3]) {
        q.reset(3);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(3);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[4]) {
        q.reset(4);
        if (q[5]) {
          q.reset(5);
          if (q[6]) {
            q.reset(6);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(6);
          }
          q.set(5);
        }
        q.set(4);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[4]) {
        q.reset(4);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(4);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[4]) {
        q.reset(4);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(4);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[2]) {
      q.reset(2);
      if (q[6]) {
        q.reset(6);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(6);
      }
      q.set(2);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[6]) {
          q.reset(6);
          if (q[7]) {
            q.reset(7);
            if (q[8]) {
              q.reset(8);
              S1();
              q.set(8);
            }
            q.set(7);
          }
          q.set(6);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[4]) {
      q.reset(4);
      if (q[5]) {
        q.reset(5);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(5);
      }
      q.set(4);
    }
    q.set(0);
  }
  if (q[0]) {
    q.reset(0);
    if (q[4]) {
      q.reset(4);
      if (q[6]) {
        q.reset(6);
        if (q[9]) {
          q.reset(9);
          S1();
          q.set(9);
        }
        q.set(6);
      }
      q.set(4);
    }
    q.set(0);
  }
}

int main() {
  cout << "Solving test..." << endl;
  q.set(); /* q = A */
  auto start = high_resolution_clock::now();
  S0(); /* start solver */
  auto stop = high_resolution_clock::now();
  auto duration = duration_cast<microseconds>(stop - start);
  cout << "Found " << i << " solutions in " << duration.count()/1000000.0f << " seconds.";
  return 0;
}
