package PisP.editor;

/*Generated by MPS */

import javax.swing.JPanel;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeId;
import org.jetbrains.mps.openapi.model.SNodeChangeListener;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.scene.Group;
import java.awt.Window;
import javax.swing.SwingUtilities;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.SceneAntialiasing;
import javafx.scene.paint.Color;
import javafx.scene.Camera;
import javafx.scene.PerspectiveCamera;
import javafx.scene.shape.Box;
import javafx.scene.paint.PhongMaterial;
import javafx.scene.transform.Rotate;
import javafx.scene.transform.Translate;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.MouseButton;
import javafx.scene.input.ScrollEvent;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.awt.Dimension;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class PieceViewer3D extends JPanel {
  public SNode node;
  public EditorContext editorContext;
  protected SNodeId id;
  protected SNodeChangeListener sncl;

  protected final int ATOM_SIZE = 50;

  private double anchorX;
  private double anchorY;
  private double anchorAngleX = 0;
  private double anchorAngleY = 0;
  private double anchorTransX = 0;
  private double anchorTransY = 0;
  private DoubleProperty angleX = new SimpleDoubleProperty(0);
  private DoubleProperty angleY = new SimpleDoubleProperty(0);
  private DoubleProperty transX = new SimpleDoubleProperty(0);
  private DoubleProperty transY = new SimpleDoubleProperty(0);
  private DoubleProperty transZ = new SimpleDoubleProperty(0);

  private Group group;


  protected void finalize() throws Throwable {
    editorContext.getModel().removeChangeListener(sncl);
    Window win = SwingUtilities.getWindowAncestor(this);
    win.dispose();
    super.finalize();
  }

  public PieceViewer3D(SNode node, EditorContext editorContext) {
    this.node = node;
    this.editorContext = editorContext;
    this.id = ((SNode) node).getNodeId();
    Platform.setImplicitExit(false);

    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        initAndShowGUI();
      }
    });
  }

  private void initAndShowGUI() {
    final JFXPanel fxPanel = new JFXPanel();
    this.add(fxPanel);
    this.setVisible(true);

    Platform.runLater(new Runnable() {
      @Override
      public void run() {
        initFX(fxPanel);
      }
    });
  }

  private void initFX(JFXPanel fxPanel) {
    Scene scene = createScene();
    fxPanel.setScene(scene);
  }

  private Scene createScene() {
    group = createGroup();
    Scene scene = new Scene(group, 400, 400, true, SceneAntialiasing.BALANCED);
    scene.setFill(Color.DARKGRAY);
    Camera camera = new PerspectiveCamera();
    camera.setNearClip(0.01);
    camera.setFarClip(6000);
    scene.setCamera(camera);
    initMouseControl(group, camera);
    return scene;
  }

  protected Group createGroup() {
    Group group = new Group();
    Box box = new Box(100, 100, 100);
    box.setMaterial(new PhongMaterial(Color.RED));
    group.getChildren().add(box);
    return group;
  }

  private void initMouseControl(Group group, Camera camera) {
    Rotate xRotate = new Rotate(0, Rotate.X_AXIS);
    Rotate yRotate = new Rotate(0, Rotate.Y_AXIS);
    Translate translate = new Translate(0, 0, 0);
    camera.getTransforms().addAll(xRotate, yRotate, translate);
    xRotate.angleProperty().bind(angleX);
    yRotate.angleProperty().bind(angleY);
    translate.xProperty().bind(transX);
    translate.yProperty().bind(transY);
    translate.zProperty().bind(transZ);

    group.setOnMousePressed((MouseEvent event) -> {
      anchorX = event.getSceneX();
      anchorY = event.getSceneY();
      anchorAngleX = angleX.get();
      anchorAngleY = angleY.get();
      anchorTransX = transX.get();
      anchorTransY = transY.get();
    });

    group.setOnMouseDragged((MouseEvent event) -> {
      if (event.getButton() == MouseButton.PRIMARY) {
        angleX.set(anchorAngleX - (anchorY - event.getSceneY()));
        angleY.set(anchorAngleY + anchorX - event.getSceneX());
      } else if (event.getButton() == MouseButton.SECONDARY) {
        transX.set(anchorTransX + anchorX - event.getSceneX());
        transY.set(anchorTransY + anchorY - event.getSceneY());
      }
    });

    group.addEventHandler(ScrollEvent.SCROLL, (ScrollEvent event) -> transZ.set(Math.min(660, transZ.get() + event.getDeltaY())));
  }

  protected ArrayList<ArrayList<Integer>> getLocations() {
    final ArrayList<ArrayList<Integer>> result = new ArrayList<>();
    editorContext.getRepository().getModelAccess().runReadAction(() -> {
      for (SNode loc : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.locations$ChQi))) {
        if (ListSequence.fromList(SLinkOperations.getChildren(loc, LINKS.coordinates$48xZ)).count() >= 3) {
          ArrayList<Integer> l = new ArrayList<Integer>();
          l.add(SPropertyOperations.getInteger(ListSequence.fromList(SLinkOperations.getChildren(loc, LINKS.coordinates$48xZ)).getElement(0), PROPS.coordinate$hw$O));
          l.add(SPropertyOperations.getInteger(ListSequence.fromList(SLinkOperations.getChildren(loc, LINKS.coordinates$48xZ)).getElement(1), PROPS.coordinate$hw$O));
          l.add(SPropertyOperations.getInteger(ListSequence.fromList(SLinkOperations.getChildren(loc, LINKS.coordinates$48xZ)).getElement(2), PROPS.coordinate$hw$O));
          result.add(l);
        }
      }
    });
    return result;
  }


  public Dimension getPreferredDimension() {
    return new Dimension(400, 400);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink coordinates$48xZ = MetaAdapterFactory.getContainmentLink(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37adb89fL, 0x2cd4be37aee65fL, "coordinates");
    /*package*/ static final SContainmentLink locations$ChQi = MetaAdapterFactory.getContainmentLink(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37ae0ae9L, 0x2cd4be37ae0e94L, "locations");
  }

  private static final class PROPS {
    /*package*/ static final SProperty coordinate$hw$O = MetaAdapterFactory.getProperty(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37adda67L, 0x2cd4be37adde2aL, "coordinate");
  }
}
