package PisP.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class bopPiecesAreOnSameLattice_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public bopPiecesAreOnSameLattice_NonTypesystemRule() {
  }
  public void applyRule(final SNode bagOfPieces, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    // Assume first piece has the correct lattice, check the rest
    if (SLinkOperations.getChildren(bagOfPieces, LINKS.pieces$2_Tv) != null) {
      if (ListSequence.fromList(SLinkOperations.getChildren(bagOfPieces, LINKS.pieces$2_Tv)).first() != null) {
        if (SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(bagOfPieces, LINKS.pieces$2_Tv)).first(), LINKS.piece$jZYy) != null) {
          String assumedLattice = SPropertyOperations.getEnum(SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(bagOfPieces, LINKS.pieces$2_Tv)).first(), LINKS.piece$jZYy), PROPS.lattice$e_Fj).getName();
          for (SNode piece : ListSequence.fromList(SLinkOperations.getChildren(bagOfPieces, LINKS.pieces$2_Tv))) {
            if (SLinkOperations.getTarget(piece, LINKS.piece$jZYy) != null) {
              if (SPropertyOperations.getEnum(SLinkOperations.getTarget(piece, LINKS.piece$jZYy), PROPS.lattice$e_Fj).getName() != assumedLattice) {
                {
                  final MessageTarget errorTarget = new NodeMessageTarget();
                  IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(piece, "This piece's lattice is mismatched with the first piece.", "r:bc41e529-dea7-4ee8-b55b-85ab02ac5dbd(PisP.typesystem)", "7684354715555857785", null, errorTarget);
                }
              }
            }
          }
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.BagOfPieces$L0;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink pieces$2_Tv = MetaAdapterFactory.getContainmentLink(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37ada031L, 0x2cd4be37aed1a3L, "pieces");
    /*package*/ static final SReferenceLink piece$jZYy = MetaAdapterFactory.getReferenceLink(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37ae02bdL, 0x2cd4be37ae080fL, "piece");
  }

  private static final class PROPS {
    /*package*/ static final SProperty lattice$e_Fj = MetaAdapterFactory.getProperty(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37ae0ae9L, 0x2cd4be37af4f8fL, "lattice");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BagOfPieces$L0 = MetaAdapterFactory.getConcept(0x9ea5405ccd504139L, 0x8b0811b78b688cf5L, 0x2cd4be37ada031L, "PisP.structure.BagOfPieces");
  }
}
