package PisP.embeddings.generator.util;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class AbstractPuzzle {
  public List<SNode> aspects;
  public List<SNode> embeddings;

  public AbstractPuzzle() {
    this.aspects = ListSequence.fromList(new ArrayList<SNode>());
    this.embeddings = ListSequence.fromList(new ArrayList<SNode>());
  }
}
